# Generated by Django 4.1.4 on 2022-12-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiEmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_column='emp_id', db_index=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(help_text='<b>Employee First Name</b>', max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='emp_images')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('joiningdate', models.DateField()),
                ('status', models.CharField(choices=[('Permanent', 'Permanent'), ('Trainee', 'Trainee')], max_length=15)),
                ('remarks', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.designation')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.district')),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.thana')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicsalary', models.FloatField()),
                ('medical', models.FloatField()),
                ('houserent', models.FloatField()),
                ('others', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.empbasicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Bachelor', 'Bachelor')], max_length=10)),
                ('institute', models.CharField(max_length=100)),
                ('passingyear', models.IntegerField()),
                ('result', models.CharField(max_length=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiEmp.empbasicinfo')),
            ],
        ),
    ]
