# Generated by Django 4.1.4 on 2023-01-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiEmp', '0002_department_designation_empbasicinfo_empsalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', related_query_name='tag', to='ApiEmp.district'),
        ),
    ]
