# Generated by Django 4.1.4 on 2023-01-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiEmp', '0004_alter_empsalary_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsalary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='ApiEmp.empbasicinfo'),
        ),
    ]
